"""Stable, language-neutral VibeFlow Core API."""

from __future__ import annotations

from vibeflow.core.compiler import (
    CompiledGraph,
    GraphCompileError,
    GraphCompiler,
    compile_core,
    explicit_flow_cycles,
)
from vibeflow.core.constants import (
    EFFECT_SCOPE_GLOBAL_STATE,
    EFFECT_SCOPE_NONE,
    EFFECT_SCOPE_TRUSTED,
    FLOW_KINDS,
    FLOW_KIND_DATA_STORE,
    FLOW_KIND_DECISION,
    FLOW_KIND_DOCUMENT,
    FLOW_KIND_GLOBAL_STATE,
    FLOW_KIND_IO,
    FLOW_KIND_PREDEFINED,
    FLOW_KIND_PREPARATION,
    FLOW_KIND_PROCESS,
    FLOW_KIND_TERMINAL,
    TARGET_FEATURE_EXECUTION_LOCKS,
    TARGET_FEATURE_GLOBAL_STATE,
)
from vibeflow.core.config.scope import (
    ConfigBindingError,
    ConfigScope,
    attach_global_config,
    config_override_conflicts,
    effective_node_params,
    merge_config_scopes,
    nested_node_config_overrides,
    node_invocation_scope,
    normalize_config_scope,
    normalize_node_config_overrides,
    scoped_node_params,
)
from vibeflow.core.contracts import (
    DataEnvelope,
    DataProvider,
    DataRequirement,
    PipelineInputSpec,
    PipelineOutputSpec,
    RunResult,
)
from vibeflow.core.flow import (
    EdgeSpec,
    ExecutionLockSpec,
    GraphConfig,
    GraphConfigError,
    NodeSpec,
    NodesetSpec,
)
from vibeflow.core.findings import Finding, HealthFinding, HealthReport
from vibeflow.core.result_scope import (
    CoverageItem,
    add_result_scope,
    format_result_scope,
    result_scope_payload,
)
from vibeflow.core.models import (
    CoreCompilation,
    CoreCompileRequest,
    ImplementationFact,
    ImplementationFacts,
    TargetFeatureSet,
    ValidatedWorkflow,
)
from vibeflow.core.config.node import (
    NodeConfigError,
    NodeConfigSpec,
    merge_node_config,
    node_config_from_call_params,
    normalize_node_config_spec,
)
from vibeflow.core.nodeset_dependencies import (
    NodesetDependency,
    NodesetDependencyGraph,
    NodesetDepthViolation,
    analyze_nodeset_dependencies,
    nodeset_dependency_cycles,
    nodeset_depth_violations,
)
from vibeflow.core.planned import PlannedBehavior
from vibeflow.core.quality import (
    ProjectQualityFacts,
    QualityFinding,
    QualityPolicy,
    SourceQualityReport,
    WorkflowQualityRequest,
    evaluate_project_quality,
    validate_workflow_quality,
)


__all__ = [
    "CompiledGraph",
    "ConfigBindingError",
    "ConfigScope",
    "CoreCompilation",
    "CoreCompileRequest",
    "CoverageItem",
    "DataEnvelope",
    "DataProvider",
    "DataRequirement",
    "EdgeSpec",
    "EFFECT_SCOPE_GLOBAL_STATE",
    "EFFECT_SCOPE_NONE",
    "EFFECT_SCOPE_TRUSTED",
    "ExecutionLockSpec",
    "FLOW_KINDS",
    "FLOW_KIND_DATA_STORE",
    "FLOW_KIND_DECISION",
    "FLOW_KIND_DOCUMENT",
    "FLOW_KIND_GLOBAL_STATE",
    "FLOW_KIND_IO",
    "FLOW_KIND_PREDEFINED",
    "FLOW_KIND_PREPARATION",
    "FLOW_KIND_PROCESS",
    "FLOW_KIND_TERMINAL",
    "Finding",
    "GraphCompileError",
    "GraphCompiler",
    "GraphConfig",
    "GraphConfigError",
    "HealthFinding",
    "HealthReport",
    "ImplementationFact",
    "ImplementationFacts",
    "ProjectQualityFacts",
    "QualityFinding",
    "QualityPolicy",
    "NodeConfigError",
    "NodeConfigSpec",
    "NodeSpec",
    "NodesetSpec",
    "NodesetDependency",
    "NodesetDependencyGraph",
    "NodesetDepthViolation",
    "PipelineInputSpec",
    "PipelineOutputSpec",
    "PlannedBehavior",
    "RunResult",
    "SourceQualityReport",
    "TargetFeatureSet",
    "TARGET_FEATURE_EXECUTION_LOCKS",
    "TARGET_FEATURE_GLOBAL_STATE",
    "ValidatedWorkflow",
    "WorkflowQualityRequest",
    "analyze_nodeset_dependencies",
    "add_result_scope",
    "attach_global_config",
    "compile_core",
    "config_override_conflicts",
    "explicit_flow_cycles",
    "format_result_scope",
    "effective_node_params",
    "evaluate_project_quality",
    "merge_config_scopes",
    "merge_node_config",
    "nested_node_config_overrides",
    "node_config_from_call_params",
    "node_invocation_scope",
    "nodeset_dependency_cycles",
    "nodeset_depth_violations",
    "normalize_config_scope",
    "normalize_node_config_overrides",
    "normalize_node_config_spec",
    "scoped_node_params",
    "result_scope_payload",
    "validate_workflow_quality",
]
