"""Target-neutral markers for project document kinds."""

from __future__ import annotations


ARCHITECTURE_DOCUMENT_HEADER = (
    "// GENERATED BY VIBEFLOW. DO NOT EDIT.\n"
    "// NON-EXECUTABLE ARCHITECTURE REVIEW DOCUMENT. EDIT SOURCE FILES AND REGENERATE.\n"
)


def is_architecture_document_text(text: str) -> bool:
    """Return whether text is a generated architecture document."""

    header = "\n".join(text.splitlines()[:4])
    return text.startswith(ARCHITECTURE_DOCUMENT_HEADER) or (
        "NON-EXECUTABLE ARCHITECTURE REVIEW DOCUMENT." in header
    )


__all__ = ["ARCHITECTURE_DOCUMENT_HEADER", "is_architecture_document_text"]
