from __future__ import annotations

import inspect
import json
from typing import Mapping

from vibeflow.compiler import CompiledGraph
from vibeflow.data_contract import providers_to_dicts, requirements_to_dicts
from vibeflow.graph_config import GraphConfig, LOOP_NODE_TYPES, LoopSpec, NodeSpec, STATUS_PLANNED
from vibeflow.graph_config.planned_behavior import effective_planned_behavior
from vibeflow.rendering.helpers import compile_for_render
from vibeflow.rendering.review_model import (
    edge_roles,
    edge_transfers,
    invocation_for_node,
    loop_field_schema,
    node_flow_kind,
    node_review_metadata,
    reachable_nodesets,
    registry_node_class,
    rendered_resources_payload,
    resources_payload,
    source_reference,
)


ARCHITECTURE_DOCUMENT_HEADER = (
    "// GENERATED BY VIBEFLOW. DO NOT EDIT.\n"
    "// NON-EXECUTABLE ARCHITECTURE REVIEW DOCUMENT. EDIT SOURCE FILES AND REGENERATE.\n"
)


def build_architecture_document(
    graph: GraphConfig,
    *,
    compiled: CompiledGraph | None = None,
    registry: object | None = None,
    resources: object | None = None,
) -> dict[str, object]:
    actual_compiled = compile_for_render(graph, compiled, registry)
    roots = _root_paths(graph)
    return {
        "workflow": _workflow_document(graph, actual_compiled, registry=registry, resources=resources),
        "nodesets": _nodesets_document(graph, registry=registry),
        "node_types": _node_types_document(graph, registry=registry, roots=roots),
        "resources": _resources_document(graph, resources, roots=roots),
    }


def render_architecture_document(
    graph: GraphConfig,
    *,
    compiled: CompiledGraph | None = None,
    registry: object | None = None,
    resources: object | None = None,
) -> str:
    payload = build_architecture_document(graph, compiled=compiled, registry=registry, resources=resources)
    return render_architecture_payload(payload)


def render_architecture_payload(payload: Mapping[str, object]) -> str:
    return ARCHITECTURE_DOCUMENT_HEADER + json.dumps(payload, indent=2, ensure_ascii=False, allow_nan=False) + "\n"


def _workflow_document(
    graph: GraphConfig,
    compiled: CompiledGraph,
    *,
    registry: object | None,
    resources: object | None,
) -> dict[str, object]:
    source = source_reference(graph.root_id, graph.root_path, graph.source_path)
    global_config = resources_payload(resources).get("global_config", {})
    return {
        "source": source,
        "global_config": _config_declaration(global_config, source=source),
        **_graph_body_document(graph, compiled, registry=registry),
    }


def _nodesets_document(graph: GraphConfig, *, registry: object | None) -> dict[str, object]:
    reachable = reachable_nodesets(graph)
    documents: dict[str, object] = {}
    for type_key, nodeset in sorted(graph.nodesets.items()):
        source = source_reference(nodeset.root_id, nodeset.root_path, nodeset.source_path)
        body = None
        if nodeset.graph.nodes:
            compiled = compile_for_render(nodeset.graph, None, registry)
            body = _graph_body_document(nodeset.graph, compiled, registry=registry)
        documents[type_key] = {
            "type_key": nodeset.type_key,
            "source": source,
            "display_name": nodeset.display_name,
            "description": nodeset.description,
            "status": nodeset.status,
            "planned_behavior": nodeset.planned_behavior.to_dict() if nodeset.status == STATUS_PLANNED else None,
            "flow_kind": nodeset.flow_kind,
            "reachable_from_workflow": type_key in reachable,
            "requires": requirements_to_dicts(nodeset.requires),
            "provides": providers_to_dicts(nodeset.provides),
            "global_config": _config_declaration(nodeset.global_config, source=source),
            "body": body,
        }
    return documents


def _graph_body_document(
    graph: GraphConfig,
    compiled: CompiledGraph,
    *,
    registry: object | None,
) -> dict[str, object]:
    return {
        "inputs": providers_to_dicts(graph.inputs),
        "outputs": requirements_to_dicts(graph.outputs),
        "max_steps": graph.max_steps,
        "nodes": [_node_document(graph, compiled, node, registry=registry) for node in graph.nodes],
        "edges": [_edge_document(graph, compiled, edge) for edge in compiled.effective_edges],
    }


def _node_document(
    graph: GraphConfig,
    compiled: CompiledGraph,
    node: NodeSpec,
    *,
    registry: object | None,
) -> dict[str, object]:
    source = source_reference(graph.root_id, graph.root_path, graph.source_path)
    invocation = invocation_for_node(graph, node)
    target = invocation.nodeset if invocation is not None else None
    planned = node.status == STATUS_PLANNED or getattr(target, "status", "") == STATUS_PLANNED
    async_config = None
    if node.async_mode:
        async_config = {"mode": node.async_mode, "result_key": node.result_key or None}
    invokes = None
    if invocation is not None:
        invokes = {
            "kind": invocation.kind,
            "target": invocation.target,
            "target_status": invocation.nodeset.status,
        }
    return {
        "id": node.id,
        "type_used": node.type_used,
        "source": source,
        "role": node_review_metadata(graph, node, registry),
        "flow_kind": node_flow_kind(node, compiled),
        "status": node.status,
        "planned_behavior": effective_planned_behavior(node, target).to_dict() if planned else None,
        "requires": requirements_to_dicts(node.requires),
        "provides": providers_to_dicts(node.provides),
        "join_policy": node.join_policy,
        "async": async_config,
        "loop": node.loop.to_dict() or None,
        "invokes": invokes,
        "config": {
            "call": _config_declaration(node.params, source=source),
            "node_configs": _config_declaration(node.node_config_overrides, source=source),
            "allow_config_override": node.allow_config_override,
        },
    }


def _edge_document(graph: GraphConfig, compiled: CompiledGraph, edge: object) -> dict[str, object]:
    return {
        "from": str(getattr(edge, "source", "")),
        "to": str(getattr(edge, "target", "")),
        "when": str(getattr(edge, "when", "")),
        "roles": list(edge_roles(compiled, edge)),
        "transfers": [_snapshot(item) for item in edge_transfers(graph, edge)],
    }


def _node_types_document(
    graph: GraphConfig,
    *,
    registry: object | None,
    roots: Mapping[str, str],
) -> dict[str, object]:
    occurrences = _node_type_occurrences(graph)
    return {
        type_key: _node_type_document(type_key, nodes, registry=registry, roots=roots)
        for type_key, nodes in sorted(occurrences.items())
    }


def _node_type_occurrences(graph: GraphConfig) -> dict[str, list[tuple[GraphConfig, NodeSpec]]]:
    occurrences: dict[str, list[tuple[GraphConfig, NodeSpec]]] = {}
    bodies = [graph, *(nodeset.graph for _, nodeset in sorted(graph.nodesets.items()))]
    for body in bodies:
        for node in body.nodes:
            if node.type_used not in LOOP_NODE_TYPES and invocation_for_node(body, node) is not None:
                continue
            occurrences.setdefault(node.type_used, []).append((body, node))
    return occurrences


def _node_type_document(
    type_key: str,
    occurrences: list[tuple[GraphConfig, NodeSpec]],
    *,
    registry: object | None,
    roots: Mapping[str, str],
) -> dict[str, object]:
    if type_key in LOOP_NODE_TYPES:
        return _loop_node_type_document(type_key, roots=roots)
    node_cls = registry_node_class(registry, type_key)
    if node_cls is None:
        owner, node = occurrences[0]
        metadata = node_review_metadata(owner, node, registry)
        return {
            "type_key": type_key,
            "source": source_reference(owner.root_id, owner.root_path, owner.source_path),
            "info": {
                "display_name": metadata["display_name"],
                "description": metadata["description"],
                "flow_kind": node.flow_kind,
            },
            "contract": None,
            "config": None,
        }
    return {
        "type_key": type_key,
        "source": _python_source(node_cls, roots=roots),
        "info": _node_info_document(getattr(node_cls, "NODE_INFO", None)),
        "contract": _node_contract_document(getattr(node_cls, "CONTRACT", None)),
        "config": _node_config_document(registry, type_key),
    }


def _loop_node_type_document(type_key: str, *, roots: Mapping[str, str]) -> dict[str, object]:
    field_schema = loop_field_schema()
    return {
        "type_key": type_key,
        "source": {
            **_python_source(LoopSpec, roots=roots),
            "runtime": {
                "module": "vibeflow.runtime.loop_mixin",
                "class": "RuntimeLoopMixin",
                "entrypoints": ["_run_loop_node", "_run_loop_block_node", "_run_while_loop"],
            },
        },
        "info": {
            "display_name": "While Loop",
            "category": "control_flow",
            "description": "Repeats one nodeset body with explicit termination, carried state, collected values, and exposed outputs.",
            "version": "",
            "flow_kind": "predefined",
            "purity": "runtime_control",
            "author": None,
            "tags": ["loop", "nodeset", "control_flow"],
            "external": False,
        },
        "contract": {
            "requires": [],
            "provides": [],
            "input_semantics": {
                "call_contract": ["Each invocation declares its complete requires list."],
                "carry": ["Each carry entry maps initial state, body input, and body update keys."],
            },
            "output_semantics": {
                "call_contract": ["Each invocation declares its complete provides list."],
                "collect": ["Collected body outputs use the declared mode and target key."],
                "outputs": ["Loop state or body outputs are exposed through explicit from/as mappings."],
            },
            "params_schema": {"node_field": "loop", "required": ["body"], "fields": field_schema},
            "output_schema": {},
        },
        "config": {
            "defaults": {
                "max_iterations": LoopSpec().max_iterations,
                "stop_when.equals": True,
                "collect[].mode": "all",
            },
            "schema": {"node_field": "loop", "termination": "exactly_one_of(stop_after, stop_when)", "fields": field_schema},
        },
    }


def _node_info_document(info: object) -> dict[str, object]:
    return {
        "display_name": str(getattr(info, "display_name", "") or ""),
        "category": str(getattr(info, "category", "") or ""),
        "description": str(getattr(info, "description", "") or ""),
        "version": str(getattr(info, "version", "") or ""),
        "flow_kind": str(getattr(info, "flow_kind", "") or ""),
        "purity": str(getattr(info, "purity", "") or ""),
        "author": getattr(info, "author", None),
        "tags": list(getattr(info, "tags", ()) or ()),
        "external": bool(getattr(info, "external", False)),
    }


def _node_contract_document(contract: object) -> dict[str, object]:
    return {
        "requires": requirements_to_dicts(tuple(getattr(contract, "requires", ()) or ())),
        "provides": providers_to_dicts(tuple(getattr(contract, "provides", ()) or ())),
        "input_semantics": _snapshot(getattr(contract, "input_semantics", {}) or {}),
        "output_semantics": _snapshot(getattr(contract, "output_semantics", {}) or {}),
        "params_schema": _snapshot(getattr(contract, "params_schema", {}) or {}),
        "output_schema": _snapshot(getattr(contract, "output_schema", {}) or {}),
    }


def _node_config_document(registry: object, type_key: str) -> dict[str, object] | None:
    try:
        config_spec = registry.get_config_spec(type_key)
    except Exception:
        return None
    return _snapshot(config_spec.to_dict())


def _resources_document(
    graph: GraphConfig,
    resources: object | None,
    *,
    roots: Mapping[str, str],
) -> dict[str, object]:
    payload = rendered_resources_payload(resources, graph)
    base_lib = payload.get("base_lib", {})
    modules = base_lib.get("modules", ()) if isinstance(base_lib, Mapping) else ()
    plugins = payload.get("plugins", ())
    return {
        "base_lib": [
            _resource_document(item, kind="base_lib", roots=roots)
            for item in sorted(modules, key=lambda item: (str(item.get("module", "")), str(item.get("id", ""))))
            if isinstance(item, Mapping)
        ],
        "plugins": [
            _resource_document(item, kind="plugin", roots=roots)
            for item in sorted(plugins, key=lambda item: (str(item.get("name", "")), str(item.get("module", ""))))
            if isinstance(item, Mapping)
        ],
    }


def _resource_document(item: Mapping[str, object], *, kind: str, roots: Mapping[str, str]) -> dict[str, object]:
    root_id = str(item.get("root_id", "") or "")
    root_path = str(item.get("root_path", "") or roots.get(root_id, ""))
    info = item.get("info", {})
    info_map = info if isinstance(info, Mapping) else {}
    common: dict[str, object] = {
        "id": str(item.get("id", "") or ""),
        "status": str(item.get("status", "implemented") or "implemented"),
        "display_name": _resource_value(item, info_map, "display_name"),
        "category": _resource_value(item, info_map, "category"),
        "description": _resource_value(item, info_map, "description"),
        "version": _resource_value(item, info_map, "version"),
        "source": source_reference(root_id, root_path, item.get("source_path", "")),
    }
    if kind == "base_lib":
        return {"module": str(item.get("module", "") or ""), **common}
    return {
        "name": str(item.get("name", "") or ""),
        "type": str(item.get("type", info_map.get("type", "")) or ""),
        "module": str(item.get("module", "") or ""),
        "class": str(item.get("class", "") or ""),
        "config_keys": sorted(str(key) for key in item.get("config_keys", ()) if isinstance(key, str)),
        **common,
    }


def _resource_value(item: Mapping[str, object], info: Mapping[str, object], field: str) -> str:
    return str(item.get(field, "") or info.get(field, "") or "")


def _config_declaration(value: object, *, source: Mapping[str, str]) -> dict[str, object]:
    return {"values": _snapshot(value), "source": dict(source)}


def _root_paths(graph: GraphConfig) -> dict[str, str]:
    roots: dict[str, str] = {}
    candidates = [(graph.root_id, graph.root_path), *((item.root_id, item.root_path) for item in graph.nodesets.values())]
    for root_id, root_path in candidates:
        if root_id and root_path:
            roots[str(root_id)] = str(root_path)
    return roots


def _python_source(node_cls: type, *, roots: Mapping[str, str]) -> dict[str, object]:
    payload: dict[str, object] = {
        "module": str(getattr(node_cls, "__module__", "") or ""),
        "class": str(getattr(node_cls, "__qualname__", getattr(node_cls, "__name__", "")) or ""),
    }
    try:
        path = inspect.getsourcefile(node_cls) or ""
        line = inspect.getsourcelines(node_cls)[1]
    except (OSError, TypeError):
        path = ""
        line = 0
    for root_id, root_path in sorted(roots.items()):
        source = source_reference(root_id, root_path, path)
        if source.get("path"):
            payload.update(source)
            break
    if line:
        payload["line"] = line
    return payload


def _snapshot(value: object) -> object:
    if isinstance(value, Mapping):
        return {str(key): _snapshot(item) for key, item in sorted(value.items(), key=lambda pair: str(pair[0]))}
    if isinstance(value, (list, tuple)):
        return [_snapshot(item) for item in value]
    return value
