"""Language-neutral resource descriptors and in-memory catalogs."""

from vibeflow.core.descriptors.catalogs import (
    BaseLibCatalog,
    CapabilityCatalog,
    DataSchemaRegistry,
    DescriptorCatalogError,
    DescriptorCatalogs,
    HostExtensionCatalog,
    NodeCatalog,
    PluginCatalog,
    SchemaRegistry,
)
from vibeflow.core.descriptors.models import (
    IMPLEMENTATION_COMPLETIONS,
    IMPLEMENTATION_LANGUAGES,
    IMPLEMENTATION_TARGETS,
    JSON_SCHEMA_2020_12,
    SOURCE_LOCATOR_KINDS,
    BaseLibDescriptor,
    CapabilityDescriptor,
    CapabilityOperation,
    CapabilityOperationDescriptor,
    CapabilityRequirement,
    CapabilityRequirementDescriptor,
    DataSchemaDescriptor,
    DescriptorModelError,
    HostExtensionDescriptor,
    ImplementationDescriptor,
    NodeContractDescriptor,
    NodeDescriptor,
    PluginDescriptor,
    SourceLocator,
)
from vibeflow.core.descriptors._resource_models import PLUGIN_TYPES
from vibeflow.core.descriptors.plugin_selection import (
    PluginResolution,
    PluginReviewRecord,
    PluginSelection,
    PluginSelectionError,
    ResolvedPluginSelection,
    review_plugin_selections,
    resolve_plugin_selections,
)

__all__ = [
    "IMPLEMENTATION_COMPLETIONS",
    "IMPLEMENTATION_LANGUAGES",
    "IMPLEMENTATION_TARGETS",
    "JSON_SCHEMA_2020_12",
    "SOURCE_LOCATOR_KINDS",
    "BaseLibCatalog",
    "BaseLibDescriptor",
    "CapabilityCatalog",
    "CapabilityDescriptor",
    "CapabilityOperation",
    "CapabilityOperationDescriptor",
    "CapabilityRequirement",
    "CapabilityRequirementDescriptor",
    "DataSchemaDescriptor",
    "DataSchemaRegistry",
    "DescriptorCatalogError",
    "DescriptorCatalogs",
    "DescriptorModelError",
    "HostExtensionCatalog",
    "HostExtensionDescriptor",
    "ImplementationDescriptor",
    "NodeCatalog",
    "NodeContractDescriptor",
    "NodeDescriptor",
    "PLUGIN_TYPES",
    "PluginCatalog",
    "PluginDescriptor",
    "PluginResolution",
    "PluginReviewRecord",
    "PluginSelection",
    "PluginSelectionError",
    "ResolvedPluginSelection",
    "SchemaRegistry",
    "SourceLocator",
    "review_plugin_selections",
    "resolve_plugin_selections",
]
